name: Release and deploy to Central

on: workflow_dispatch

jobs:
  release-checks:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.5.0
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - name: Release checks and update version for release
        run: |
          /scripts/release-checks.sh --java --maven pom.xml
          /scripts/finalize-version.sh --java --maven pom.xml
        shell: bash
  deploy-central:
    needs: release-checks
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
      version: ${{ steps.build.outputs.version }}
    container: zepben/pipeline-java
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: /maven
          key: maven

      - name: Checkout release branch
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git checkout release
        shell: bash

      - name: Maven deploy to Central
        id: build
        uses: zepben/maven-deploy-central-action@main
        with:
          ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
        continue-on-error: true

      - name: Upload coverage to Codecov
        if: steps.build.outcome == 'success'
        uses: codecov/codecov-action@v1

      - uses: actions/upload-artifact@master
        if: steps.build.outcome == 'success'
        with:
          name: ${{ steps.build.outputs.artifact }}
          path: ${{ steps.build.outputs.artifact-path }}

      - name: Fail build
        if: steps.build.outcome == 'failure'
        run: |
          git push origin -d release
          echo "There was an error in the mvn deploy command above."
          exit 1
        shell: bash

  build-docs:
    needs: [deploy-central]
    runs-on: ubuntu-latest
    outputs:
      artifact: docs
    container: node:12-alpine
    steps:
      - name: Install Git
        run: |
          apk add git

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: bash
ï¿¼

      - uses: actions/checkout@v2

      - name: Cache nodejs deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm

      - name: Build docusaurus
        id: build
        uses: zepben/docusaurus-action@main
        with:
          VERSION: ${{ needs.deploy-central.outputs.version }}
          NPM_REPO: ${{ secrets.NPM_REPO }}
          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        continue-on-error: true

      - uses: actions/upload-artifact@master
        if: steps.build.outcome == 'success'
        with:
          name: docs
          path: docs/build/

      - name: Fail build
        if: steps.build.outcome == 'failure'
        run: | 
          git push origin -d release
          echo "There was an error in the docusaurus build above."
          exit 1
        shell: sh

  create-release:
    needs: [deploy-central, build-docs]
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Merge and Tag
        id: merge
        run: | 
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch --all
          git merge origin/release
          git push origin ${GITHUB_REF/refs\/heads\//}
          artifactId=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
          artifact="${artifactId}-${version}.jar"
          git tag "v$version"
          git push --tags
          echo "::set-output name=tag::$(echo v$version)"
          echo "::set-output name=artifact::$(echo $artifact)"
          echo "::set-output name=artifact-path::$(echo target/$artifact)"
        shell: bash
        continue-on-error: true

      - name: Fail
        if: steps.merge.outcome == 'failure'
        run: | 
          git push origin -d release
          echo "There was an error in merging the branch. release branch was deleted."
          exit 1
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.merge.outputs.tag }}
          release_name: ${{ steps.merge.outputs.tag }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.deploy-central.outputs.artifact }}
          path: built-artifacts

      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs-site

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: built-artifacts/${{ needs.deploy-central.outputs.artifact }}
          asset_name: ${{ needs.deploy-central.outputs.artifact }}
          asset_content_type: application/zip

      - name: Zip documentation
        run: |
          cd docs-site
          zip -r docs-site.zip .
        shell: bash

      - name: Upload docs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: docs-site/docs-site.zip
          asset_name: docs-site.zip
          asset_content_type: application/zip

      - name: Deploy documentation
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: ${{ secrets.DOCS_REPO }}
          event-type: ${{ secrets.DOCS_REPO_EVOLVE_WORKFLOW }}
          client-payload: '{"product_key": "jvm-sdk", "download_url": "https://github.com/${{ github.repository }}/releases/download/${{ steps.merge.outputs.tag }}/docs-site.zip"}'

  update-version:
    needs: create-release
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.5.0
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - name: Update to next minor version
        run: |
          /scripts/update-version.sh --java --maven --release pom.xml changelog.md
        shell: bash
