name: Maven Library Release

on: workflow_dispatch

jobs:
  release:
    uses: zepben/.github/.github/workflows/maven-lib-release-with-docs.yml@main
    with:
      private: false
      product-key: "jvm-sdk"
      licencecheck: true
    secrets: inherit
